theme: jekyll-theme-minimal
title: Space of Xi's daily thoughts
description: This is a personal website where I'll present part of my thoughts on things in daily life. The content (otherwise stated) presented on this site is my original work. All rights reserved. Feel free to leave your comments via e-mail -- dr dot huangxi at gmail dot com.
