theme: jekyll-theme-minimal
title: Space of Xi's thoughts
description: This is a personal website where I'll present part of my thoughts on things in daily life. The content (otherwise stated) presented on this site is my original work. All rights reserved. Feel free to leave your comments via e-mail -- dr dot huangxi at gmail dot com.


# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: 'yundert'

# permalink: /:year/:month/:title
paginate: 5

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate', 'jekyll-feed']

exclude: ['README.md', 'LICENSE.md']
